### ISSUE TITLE
Einbindung DWD Wetterdaten

### ISSUE THREAD

**Issue by ju97** [Kreiswasserwacht-Wurzburg/digitales_wachbuch#11]
Wetterdaten vom DWD auf dem Dashboard einbinden. Besondere Darstellung und Kennzeichnung bestimmter Wetterwarnungen.  

[https://opendata.dwd.de/](https://opendata.dwd.de/)

[https://maps.dwd.de/geoserver/web/](https://maps.dwd.de/geoserver/web/)

**Comment by pwueje** [comment]
Implemented
