### ISSUE TITLE
Systemwert Land / Region definieren

### ISSUE THREAD

**Issue by thomasscheuermann** [Kreiswasserwacht-Wurzburg/digitales_wachbuch#25]
Im Header wird die Uhrzeit aktuell im Format en-US ausgegeben. Im Projekt sollte systemweit als Land / Region de-DE gesetzt werden.

**Comment by pwueje** [comment]
Prüfe Mal bitte deine Browser-Einstellungen. Das Format wird abhängig vom Systemformat gesetzt.

Ich bin aus Gründen der Portabilität gegen ein festlegen auf ein fixes Format

**Comment by thomasscheuermann** [comment]
Meine Systemeinstellungen / Region stimmen. Kann es evtl. sein, dass wir dies bei azurewebsites.net dies ändern müssen?

**Comment by pwueje** [comment]
Müssen wir prüfen wo das hängt. Bei mir im Entwicklungssystem ist es das deutsche Format. 

Ich schaue es mir an
