### ISSUE TITLE
Entscheidung über verwendeten Technologiestack

### ISSUE THREAD

**Issue by mawux** [Kreiswasserwacht-Wurzburg/digitales_wachbuch#8]

**Comment by amens** [comment]
Die Anwendung soll mit .NET Core 3.1 und Serverside Blazor entwickelt werden. Als Datenbank kann jede vom Entity Framework Core unterstütze Datenbank-Engine verwendet werden. Es bietet sich jedoch an auf den MS Sql Server zu setzen.
